mdm_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: mdmBundle:Default:index }

mdm_form_task:
    pattern:  /createTasks/
    defaults: { _controller: mdmBundle:Default:createTasks }
    
mdm_form_users:
    pattern:  /form_users/
    defaults: { _controller: mdmBundle:Default:formUsers }
    
mdm_form_login:
    pattern:  /login/
    defaults: { _controller: mdmBundle:Default:formlogin }

mdm_user_signup:
    pattern:  /signup/
    defaults: { _controller: mdmBundle:Default:signup }


mdm_tasks_user:
    pattern:    /allTasks/{id}
    defaults:   { _controller: mdmBundle:Default:AllTaskUser }
    
mdm_tasks_group:
    pattern: /tasksgroup/{id}/
    defaults:   { _controller: mdmBundle:Default:tasksGroup }
    
    
mdm_tasks_delete:
     pattern: /deletetask/{id}/
     defaults:   { _controller: mdmBundle:Default:deleteTask }
    